-- Auth + Moderation + Tiering schema migration
--
-- This migration adds:
--   1. NextAuth.js required tables (users, accounts, sessions, verification_token)
--   2. Contributor identity extension on top of users
--   3. Moderator invite + role system
--   4. Moderation audit log
--   5. Tier columns on equation_matches
--
-- NextAuth table names and column types follow the @auth/pg-adapter schema
-- exactly. If you change them, the adapter will fail silently on insert.
-- Reference: https://authjs.dev/getting-started/adapters/pg

-- ==========================================================================
-- NextAuth.js required tables
-- ==========================================================================

CREATE TABLE IF NOT EXISTS verification_token (
    identifier  TEXT NOT NULL,
    expires     TIMESTAMPTZ NOT NULL,
    token       TEXT NOT NULL,
    PRIMARY KEY (identifier, token)
);

CREATE TABLE IF NOT EXISTS accounts (
    id                   SERIAL,
    "userId"             INTEGER NOT NULL,
    type                 VARCHAR(255) NOT NULL,
    provider             VARCHAR(255) NOT NULL,
    "providerAccountId"  VARCHAR(255) NOT NULL,
    refresh_token        TEXT,
    access_token         TEXT,
    expires_at           BIGINT,
    id_token             TEXT,
    scope                TEXT,
    session_state        TEXT,
    token_type           TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sessions (
    id             SERIAL,
    "userId"       INTEGER NOT NULL,
    expires        TIMESTAMPTZ NOT NULL,
    "sessionToken" VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
    id             SERIAL,
    name           VARCHAR(255),
    email          VARCHAR(255),
    "emailVerified" TIMESTAMPTZ,
    image          TEXT,
    PRIMARY KEY (id)
);

-- Indexes NextAuth expects
CREATE UNIQUE INDEX IF NOT EXISTS accounts_provider_provider_account_id_idx
    ON accounts(provider, "providerAccountId");
CREATE UNIQUE INDEX IF NOT EXISTS sessions_session_token_idx
    ON sessions("sessionToken");
CREATE UNIQUE INDEX IF NOT EXISTS users_email_idx
    ON users(email)
    WHERE email IS NOT NULL;

-- ==========================================================================
-- Contributor identity + role
-- ==========================================================================
-- Extends users with Analog Quest-specific identity data. We keep this as a
-- separate table rather than adding columns to users so NextAuth's adapter
-- doesn't get confused and we can evolve our schema independently.

CREATE TABLE IF NOT EXISTS contributors (
    user_id        INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    github_id      BIGINT UNIQUE,      -- GitHub's immutable numeric user ID
    github_login   TEXT UNIQUE,        -- cached username (changes allowed, refreshed on login)
    avatar_url     TEXT,               -- cached GitHub avatar
    role           TEXT NOT NULL DEFAULT 'contributor'
                   CHECK (role IN ('contributor', 'moderator', 'admin')),
    joined_at      TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at   TIMESTAMPTZ DEFAULT NOW(),

    -- Aggregate stats (denormalized for fast profile page reads)
    submissions_count           INTEGER NOT NULL DEFAULT 0,
    contributions_to_verified   INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS contributors_role_idx ON contributors(role);
CREATE INDEX IF NOT EXISTS contributors_github_login_idx ON contributors(github_login);

-- ==========================================================================
-- Moderator invite system
-- ==========================================================================
-- Single-use tokens generated by admins, redeemed by a signed-in GitHub user
-- to promote themselves to the 'moderator' role.

CREATE TABLE IF NOT EXISTS moderator_invites (
    id              SERIAL PRIMARY KEY,
    token           TEXT UNIQUE NOT NULL,
    created_by      INTEGER REFERENCES users(id),
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL,
    redeemed_by     INTEGER REFERENCES users(id),
    redeemed_at     TIMESTAMPTZ,
    note            TEXT  -- optional: "for jane who runs the dynamical systems group"
);

CREATE INDEX IF NOT EXISTS moderator_invites_token_idx ON moderator_invites(token);
CREATE INDEX IF NOT EXISTS moderator_invites_unredeemed_idx
    ON moderator_invites(expires_at)
    WHERE redeemed_by IS NULL;

-- ==========================================================================
-- Moderation audit log
-- ==========================================================================
-- Append-only record of every moderator action. Used for accountability,
-- dispute resolution, and reversal of rogue decisions.

CREATE TABLE IF NOT EXISTS moderation_log (
    id              SERIAL PRIMARY KEY,
    moderator_id    INTEGER NOT NULL REFERENCES users(id),
    action          TEXT NOT NULL
                    CHECK (action IN ('promote_tier_2', 'promote_tier_3',
                                      'promote_tier_4', 'reject', 'unreject',
                                      'demote', 'note')),
    target_type     TEXT NOT NULL
                    CHECK (target_type IN ('equation_match', 'isomorphism',
                                           'extraction', 'contributor')),
    target_id       INTEGER NOT NULL,
    reason          TEXT,   -- from fixed enum when action=reject, else free-form
    note            TEXT,   -- moderator's written justification (required for promotions)
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS moderation_log_target_idx
    ON moderation_log(target_type, target_id);
CREATE INDEX IF NOT EXISTS moderation_log_moderator_idx
    ON moderation_log(moderator_id);
CREATE INDEX IF NOT EXISTS moderation_log_created_idx
    ON moderation_log(created_at DESC);

-- ==========================================================================
-- Tier columns on equation_matches
-- ==========================================================================
-- Everything the pipeline produces is Tier 1 by default. Moderators promote
-- individual matches to higher tiers with written justification.

ALTER TABLE equation_matches
    ADD COLUMN IF NOT EXISTS tier TEXT NOT NULL DEFAULT 'tier_1_syntactic'
        CHECK (tier IN ('tier_1_syntactic', 'tier_2_structural',
                        'tier_3_transferable', 'tier_4_validated'));

ALTER TABLE equation_matches
    ADD COLUMN IF NOT EXISTS tier_note TEXT;

ALTER TABLE equation_matches
    ADD COLUMN IF NOT EXISTS tier_promoted_by INTEGER REFERENCES users(id);

ALTER TABLE equation_matches
    ADD COLUMN IF NOT EXISTS tier_promoted_at TIMESTAMPTZ;

ALTER TABLE equation_matches
    ADD COLUMN IF NOT EXISTS rejected_reason TEXT
        CHECK (rejected_reason IS NULL OR rejected_reason IN (
            'not_cross_domain',
            'parser_error',
            'superficial_match',
            'trivial_form',
            'standard_canonical_object',
            'duplicate',
            'other'
        ));

-- ==========================================================================
-- Trivial hashes (moderator-learned trivia filter)
-- ==========================================================================
-- When a moderator rejects a match with reason 'standard_canonical_object',
-- the canonical form's structure_hash is added here. Future matches whose
-- structure_hash is in this table are never created in the first place —
-- the matcher joins against this table and excludes listed hashes.
--
-- This gives the system a way to learn from moderator decisions: common
-- textbook objects (the S^2 metric, F=ma, the heat equation, the SGD
-- update rule, the Pythagorean theorem) get surfaced once, rejected once,
-- and then never surfaced again.
--
-- The list can be cleared or individual hashes removed by an admin from
-- the admin surface. example_latex is stored so a human browsing the
-- trivia list can see what each hash represents without having to look
-- it up in the equations table.

CREATE TABLE IF NOT EXISTS trivial_hashes (
    structure_hash  TEXT PRIMARY KEY,
    added_by        INTEGER REFERENCES users(id),
    added_at        TIMESTAMPTZ DEFAULT NOW(),
    reason          TEXT,
    example_latex   TEXT
);

CREATE INDEX IF NOT EXISTS equation_matches_tier_idx ON equation_matches(tier);
CREATE INDEX IF NOT EXISTS equation_matches_pending_review_idx
    ON equation_matches(created_at DESC)
    WHERE tier = 'tier_1_syntactic' AND status = 'candidate';

-- ==========================================================================
-- Contributor attribution on extractions
-- ==========================================================================
-- The existing extractions table uses contributor_token (free-form string).
-- Add a user_id reference so we can attribute submissions to GitHub-auth users.
-- The old contributor_token column stays for backwards compatibility and for
-- any legacy submissions (there are none, but defensive).

ALTER TABLE extractions
    ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id);

CREATE INDEX IF NOT EXISTS extractions_user_id_idx ON extractions(user_id);

-- Same for equations: attribute which pipeline contributor submitted each row
ALTER TABLE equations
    ADD COLUMN IF NOT EXISTS submitted_by_user_id INTEGER REFERENCES users(id);

CREATE INDEX IF NOT EXISTS equations_submitted_by_idx ON equations(submitted_by_user_id);

-- ==========================================================================
-- CLI tokens (for agent authentication)
-- ==========================================================================
-- Long-lived bearer tokens that agents use to authenticate API calls.
-- The copy-to-agent flow generates one of these on demand and embeds it
-- in the copied message. Users can revoke them from their profile.
-- We store a SHA-256 hash of the token, not the token itself, so a DB
-- leak doesn't immediately grant access.

CREATE TABLE IF NOT EXISTS cli_tokens (
    id              SERIAL PRIMARY KEY,
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash      TEXT NOT NULL UNIQUE,
    label           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    last_used_at    TIMESTAMPTZ,
    revoked_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS cli_tokens_user_idx ON cli_tokens(user_id);
CREATE INDEX IF NOT EXISTS cli_tokens_active_idx
    ON cli_tokens(token_hash) WHERE revoked_at IS NULL;
